<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>findSpecialtyByCodeUsingGET</name>
   <tag></tag>
   <elementGuidId>9d9a5b39-89ae-4c66-a74e-a02cab120390</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-type</name>
      <type>Main</type>
      <value>*/*</value>
   </httpHeaderProperties>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://localhost:9098/clevehr-services/api/v1/specialties/${specialtyCode}${/lang/}${lang}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceFunction></soapServiceFunction>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>acce7646-046f-43d7-a317-d8af92815a71</id>
      <masked>false</masked>
      <name>lang</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>66713a9f-c6f5-45e3-b408-9df29e1635ed</id>
      <masked>false</masked>
      <name>specialtyCode</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
